# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-05-25 16:41:16
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    N50_DEM = arcpy.Raster("\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_DEM")
    Input_false_raster_or_constant_value = 0

    # Process: Fill (Fill) (sa)
    N50_Filled = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_Filled"
    Fill = N50_Filled
    N50_Filled = arcpy.sa.Fill(N50_DEM, None)
    N50_Filled.save(Fill)


    # Process: Flow Direction (Flow Direction) (sa)
    N50_FlowDir = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_FlowDir"
    Flow_Direction = N50_FlowDir
    N50_DropRast = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_DropRast"
    N50_FlowDir = arcpy.sa.FlowDirection(N50_Filled, "NORMAL", N50_DropRast, "D8")
    N50_FlowDir.save(Flow_Direction)

    N50_DropRast = arcpy.Raster(N50_DropRast)

    # Process: Flow Accumulation (Flow Accumulation) (sa)
    N50_FlowAcc = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_FlowAcc"
    Flow_Accumulation = N50_FlowAcc
    N50_FlowAcc = arcpy.sa.FlowAccumulation(N50_FlowDir, "", "FLOAT", "D8")
    N50_FlowAcc.save(Flow_Accumulation)


    # Process: Con (Con) (ia)
    N50_FlowAcc_1k = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_FlowAcc_1k"
    Con = N50_FlowAcc_1k
    N50_FlowAcc_1k = arcpy.ia.Con(N50_FlowAcc, N50_FlowAcc, Input_false_raster_or_constant_value, "VALUE > 1000")
    N50_FlowAcc_1k.save(Con)


    # Process: Stream Order (Stream Order) (sa)
    N50_StreamOrder_1k = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_StreamOrder_1k"
    Stream_Order = N50_StreamOrder_1k
    N50_StreamOrder_1k = arcpy.sa.StreamOrder(N50_FlowAcc_1k, N50_FlowDir, "STRAHLER")
    N50_StreamOrder_1k.save(Stream_Order)


    # Process: Stream to Feature (Stream to Feature) (sa)
    Streams_1k = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\Streams_1k"
    arcpy.sa.StreamToFeature(N50_StreamOrder_1k, N50_FlowDir, Streams_1k, "SIMPLIFY")

    # Process: Stream Link (Stream Link) (sa)
    N50_StreamLink_1k = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_StreamLink_1k"
    Stream_Link = N50_StreamLink_1k
    N50_StreamLink_1k = arcpy.sa.StreamLink(N50_StreamOrder_1k, N50_FlowDir)
    N50_StreamLink_1k.save(Stream_Link)


    # Process: Watershed (Watershed) (sa)
    N50_Watershed = "\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb\\N50_Watershed"
    Watershed = N50_Watershed
    N50_Watershed = arcpy.sa.Watershed(N50_FlowDir, N50_StreamLink_1k, "VALUE")
    N50_Watershed.save(Watershed)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb", workspace="\\\\hume.uio.no\\student-u86\\pmhalvor\\pc\\Dokumenter\\ArcGIS\\Projects\\GIS10\\GIS10.gdb"):
        Model()
